app = "clarity-backend"
primary_region = "iad"

[env]
  NODE_ENV = "production"
  PORT = "3001"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    soft_limit = 100
    hard_limit = 200

[checks]
  [checks.status]
    port = 3001
    type = "http"
    method = "get"
    path = "/"
    interval = "15s"
    timeout = "2s"

[vm]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1


